### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Foxiseminger** [FireMario211/Object-Workshop#2]
game crashes every time i open the button in the editor

**Comment by FireMario211** [comment]
logs?

**Comment by Foxiseminger** [comment]
sure
2024-09-04T19:14:47-0400
To the mod developer: Please 309 yourself

== Geode Information ==
- Working Directory: C:\Users\foxis\OneDrive\Desktop\Geometry.Dash.v2.206a
- Loader Version: v3.4.0 (Geometry Dash v2.206)
- Loader Commit: a533b5f
- Bindings Commit: de6a02b
- Installed Mods: 39 (Loaded: 39/39)
- Problems: 0

== Exception Information ==
- Thread Information: "Main" (ID: 11532)
- Thread Start Address: GeometryDash.exe+0x4A41C8 (<0x4a41c8>+0x0)
- Exception Code: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
- Exception Address: camila314.custombg.dll+0x3BF2 (<0x3a70>+0x182)
- Exception Flags: 0x0
- Exception Parameters: 0x0, 0x1B4
- Access Violation Type: Read
- Access Violation Address: 0x000001B4
- Protect: PAGE_NOACCESS (0x1)
- State: MEM_FREE (0x10000)
- Type: Unknown (0x0)

== Stack Trace ==
- camila314.custombg.dll+0x3BF2 (<0x3a70>+0x182)
- 0x280DFDD5472+0x0
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- Geode.dll+0x1F80A3 (geode::ScrollLayer::visit+0x123)
└ /home/runner/work/geode/geode/loader/src/ui/nodes/ScrollLayer.cpp:45
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- alphalaneous.happy_textures.dll+0x6AAFB
- 0x280DFDD5472+0x0
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- libcocos2d.dll+0x5788 (cocos2d::CCNode::visit+0xc8)
- libcocos2d.dll+0xBBC70 (cocos2d::CCDirector::drawScene+0x70)
- libcocos2d.dll+0xBC33B (<0xbc2c0>+0x7b)
- libcocos2d.dll+0x72CD2 (cocos2d::CCApplication::run+0x462)
- GeometryDash.exe+0x4A2D69 (<0x4a2ca6>+0xc3)
- Geode.dll+0x2453DA (gdMainHook+0x22a)
└ /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167
- GeometryDash.exe+0x4A415A (__scrt_common_main_seh+0x106)
- KERNEL32.DLL+0x17374 (BaseThreadInitThunk+0x14)
- ntdll.dll+0x4CC91 (RtlUserThreadStart+0x21)

== Register States ==
- RAX: 28092B4C3AC (&"")
- RBX: 00000000 (0i | 0u)
- RCX: 28092B4C340 (-> 0x7FFDF28262C8 -> &"")
- RDX: 280DFA80000 (&"")
- RBP: 00000000 (0i | 0u)
- RSP: D3F97CFD60 (&"")
- RDI: 00000000 (0i | 0u)
- RSI: 00000000 (0i | 0u)
- R8: 280DFBA2C40 (-> 0x280DFBA0CF0 -> 0x2CF000F)
- R9: 00000001 (1i | 1u)
- R10: 00008000 (32768i | 32768u)
- R11: D3F97CED50 (-> 0x1)
- R12: 00000000 (0i | 0u)
- R13: 00000000 (0i | 0u)
- R14: 00000000 (0i | 0u)
- R15: 00000000 (0i | 0u)
- RIP: 7FFE259FCC91 (ntdll.dll+0x4CC91 (RtlUserThreadStart+0x21))
- XMM0: 653A3A6432736F63 6F63207373616C63 (5.496483e+22 | 1.4169788e-08 | 7.0292326e+28 | 1.7859881e+31)
- XMM1: 653A3A6432736F63 6F63207373616C63 (5.496483e+22 | 1.4169788e-08 | 7.0292326e+28 | 1.7859881e+31)
- XMM2: 7B00100500000000 0000000141000000 (6.649389e+35 | 0 | 1e-45 | 8)
- XMM3: 0000000000000000 000000003E000000 (0 | 0 | 0 | 0.125)
- XMM4: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- XMM5: 6E6F69736E657478 653A3A6432736F63 (1.8523599e+28 | 1.7753217e+28 | 5.496483e+22 | 1.4169788e-08)
- XMM6: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- XMM7: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- AF: 0 | CF: 0 | DF: 0 
- IF: 1 | OF: 0 | PF: 1 
- SF: 0 | TF: 0 | ZF: 1 

== Installed Mods ==
x | [v1.0.0-beta.2] alphalaneous.editortab_api
x | [v1.4.3] alphalaneous.happy_textures
x | [v1.1.3] alphalaneous.transparent_lists
x | [v1.2.5] blueblock6.cleanstartpos
x | [v1.1.1] camila314.custombg
x | [v1.0.4] capeling.startpos_switcher
x | [v1.0.3] colon.gold_user_coins
x | [v4.2.8] cvolton.betterinfo
x | [v1.1.0] cvolton.compact_lists
x | [v1.0.1] cvolton.level-id-api
x | [v1.2.1] cvolton.misc_bugfixes
x | [v1.0.1] fig.authentication
x | [v1.0.9] firee.goldenbest
x | [v1.0.5] firee.object-workshop
x | [v0.3.1] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.2] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.4.8] hiimjustin000.fake_rate
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.0.0] hjfod.bettersave_recovery
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.1.4] km7dev.gdps-switcher
x | [v1.3.3] legowiifun.unlisted_objects_in_editor
x | [v1.0.0-beta.41] minemaker0430.gddp_integration
x | [v2.3.0] naxrin.transparent
x | [v1.6.0] prevter.bettercrash
x | [v1.0.0] sabe.trailfix
x | [v4.2.0-beta.1] spaghettdev.betterinputs
x | [v1.2.5] the_bearodactyl.gay-wave-trail
x | [v1.6.4] thesillydoggo.qolmod
x | [v1.12.7] undefined0.gdtweaks
x | [v1.3.3] uproxide.textures
x | [v1.1.4] weebify.restartbtn

== Stack Allocations ==
- 0xD3F97CDB60: 00000000 (0i | 0u)
- 0xD3F97CDB68: 00000000 (0i | 0u)
- 0xD3F97CDB70: 0000027F (639i | 639u)
- 0xD3F97CDB78: 00000000 (0i | 0u)
- 0xD3F97CDB80: 00000000 (0i | 0u)
- 0xD3F97CDB88: FFFF00001FA7 (281470681751463i | 8103u)
- 0xD3F97CDB90: 00000000 (0i | 0u)
- 0xD3F97CDB98: 00000000 (0i | 0u)
- 0xD3F97CDBA0: 00000000 (0i | 0u)
- 0xD3F97CDBA8: 00000000 (0i | 0u)
- 0xD3F97CDBB0: 00000000 (0i | 0u)
- 0xD3F97CDBB8: 00000000 (0i | 0u)
- 0xD3F97CDBC0: 00000000 (0i | 0u)
- 0xD3F97CDBC8: 00000000 (0i | 0u)
- 0xD3F97CDBD0: 00000000 (0i | 0u)
- 0xD3F97CDBD8: 00000000 (0i | 0u)
- 0xD3F97CDBE0: 00000000 (0i | 0u)
- 0xD3F97CDBE8: 00000000 (0i | 0u)
- 0xD3F97CDBF0: 00000000 (0i | 0u)
- 0xD3F97CDBF8: 00000000 (0i | 0u)
- 0xD3F97CDC00: 00000000 (0i | 0u)
- 0xD3F97CDC08: 00000000 (0i | 0u)
- 0xD3F97CDC10: 5A38000060000 (1587145035087872i | 393216u)
- 0xD3F97CDC18: 280E92E9870 (-> 0x7FFDBD453C88 -> 0x7FFDBC9689C0 -> igxelpicd64.dll+0x789C0 (<0x789c0>+0x0))
- 0xD3F97CDC20: 28092B08670 (-> 0x280E92D1B40 -> &"")
- 0xD3F97CDC28: 50F4000060000 (1424142436270080i | 393216u)
- 0xD3F97CDC30: 280E92E8C90 (-> 0x7FFDBD453C88 -> 0x7FFDBC9689C0 -> igxelpicd64.dll+0x789C0 (<0x789c0>+0x0))
- 0xD3F97CDC38: 280E94104E0 (-> 0x280E92D1B40 -> &"")
- 0xD3F97CDC40: 596E000060000 (1573263700787200i | 393216u)
- 0xD3F97CDC48: 280E92E9870 (-> 0x7FFDBD453C88 -> 0x7FFDBC9689C0 -> igxelpicd64.dll+0x789C0 (<0x789c0>+0x0))
- 0xD3F97CDC50: 28092B08670 (-> 0x280E92D1B40 -> &"")
- 0xD3F97CDC58: 4F60000060000 (1396379767668736i | 393216u)
- 0xD3F97CDC60: 280E92E8C90 (-> 0x7FFDBD453C88 -> 0x7FFDBC9689C0 -> igxelpicd64.dll+0x789C0 (<0x789c0>+0x0))
- 0xD3F97CDC68: 280E94104E0 (-> 0x280E92D1B40 -> &"")
- 0xD3F97CDC70: 00000000 (0i | 0u)
- 0xD3F97CDC78: 00000000 (0i | 0u)
- 0xD3F97CDC80: 00000000 (0i | 0u)
- 0xD3F97CDC88: 00000000 (0i | 0u)
- 0xD3F97CDC90: 00000000 (0i | 0u)
- 0xD3F97CDC98: 00000000 (0i | 0u)
- 0xD3F97CDCA0: 00000000 (0i | 0u)
- 0xD3F97CDCA8: 00000000 (0i | 0u)
- 0xD3F97CDCB0: 00000000 (0i | 0u)
- 0xD3F97CDCB8: 00000000 (0i | 0u)
- 0xD3F97CDCC0: 00000000 (0i | 0u)
- 0xD3F97CDCC8: 00000000 (0i | 0u)
- 0xD3F97CDCD0: 00000000 (0i | 0u)
- 0xD3F97CDCD8: 00000000 (0i | 0u)
- 0xD3F97CDCE0: 00000000 (0i | 0u)
- 0xD3F97CDCE8: 00000000 (0i | 0u)
- 0xD3F97CDCF0: 00000000 (0i | 0u)
- 0xD3F97CDCF8: 00000000 (0i | 0u)
- 0xD3F97CDD00: 00000000 (0i | 0u)
- 0xD3F97CDD08: 00000000 (0i | 0u)
- 0xD3F97CDD10: 280E4D8D1B0 (-> 0x280E4D8D220 -> &"")
- 0xD3F97CDD18: 280E4D912B0 (-> 0x280E4D91320 -> &"")
- 0xD3F97CDD20: 280ED0A0574 (-> 0x780C0A0000000001)
- 0xD3F97CDD28: 7FFDBCBD5076 (igxelpicd64.dll+0x2E5076 (<0x2e4fcc>+0xaa))
- 0xD3F97CDD30: 280E4D8C8F0 (-> 0x1D936)
- 0xD3F97CDD38: 280ED220004 (-> 0x780C0A0000000001)
- 0xD3F97CDD40: 280ED220004 (-> 0x780C0A0000000001)
- 0xD3F97CDD48: 280ED0A0574 (-> 0x780C0A0000000001)
- 0xD3F97CDD50: 28000000000 (2748779069440i | 0u)
- 0xD3F97CDD58: 7FFDBC961F7E (igxelpicd64.dll+0x71F7E (<0x71e74>+0x10a))
- 0xD3F97CDD60: 280E4D8BBB0 (-> 0x7FFDBD4533C0 -> 0x7FFDBD370390 -> igxelpicd64.dll+0xA80390 (<0xa80390>+0x0))
- 0xD3F97CDD68: 7FFDBC9072FD (igxelpicd64.dll+0x172FD)
- 0xD3F97CDD70: 280E49321F0 (&"0")
- 0xD3F97CDD78: 280E6BF07C0 (&"")
- 0xD3F97CDD80: A23DACEF1FAD (178385778057133i | 2901352365u)
- 0xD3F97CDD88: 00000004 (4i | 4u)
- 0xD3F97CDD90: 408E6666 (1083074150i | 1083074150u)
- 0xD3F97CDD98: 00000000 (0i | 0u)
- 0xD3F97CDDA0: 00000001 (1i | 1u)
- 0xD3F97CDDA8: 00000004 (4i | 4u)
- 0xD3F97CDDB0: 280E4D8C8E0 (&"")
- 0xD3F97CDDB8: 280E4D8C8E0 (&"")
- 0xD3F97CDDC0: 280E4D56D00 (&"")
- 0xD3F97CDDC8: 280E4D97801 (&"")
- 0xD3F97CDDD0: D3F97CDEE0 (-> 0xA23DACEF014D)
- 0xD3F97CDDD8: 7FFDBC91C408 (igxelpicd64.dll+0x2C408 (<0x2b599>+0xe6f))
- 0xD3F97CDDE0: 280E492E8A0 (-> 0x280E92D1B40 -> &"")
- 0xD3F97CDDE8: 7FFDBCBD5076 (igxelpicd64.dll+0x2E5076 (<0x2e4fcc>+0xaa))
- 0xD3F97CDDF0: 280E4D97810 (-> 0x101010101010001)
- 0xD3F97CDDF8: D3F97CE080 (-> 0x7FFE1524A7BC -> 0x57B2000056D6)
- 0xD3F97CDE00: 00000000 (0i | 0u)
- 0xD3F97CDE08: 00000000 (0i | 0u)
- 0xD3F97CDE10: 800400000000 (140754668224512i | 0u)
- 0xD3F97CDE18: 0000001D (29i | 29u)
- 0xD3F97CDE20: 00000000 (0i | 0u)
- 0xD3F97CDE28: 280E4931690 (-> 0x280E92D1B40 -> &"")
- 0xD3F97CDE30: 280E49321F0 (&"0")
- 0xD3F97CDE38: 280E6BF07C0 (&"")
- 0xD3F97CDE40: 4E4D97C70 (21019327600i | 3839458416u)
- 0xD3F97CDE48: 280E6BF07B0 (-> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 [...])
- 0xD3F97CDE50: 00000001 (1i | 1u)
- 0xD3F97CDE58: 280E49B0B60 (&"")
- 0xD3F97CDE60: 280E6BF07B0 (-> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 -> 0x280E6BEFF30 -> 0x280E6BF07B0 [...])
- 0xD3F97CDE68: 7FFDBCBD26F2 (igxelpicd64.dll+0x2E26F2 (<0x2e2680>+0x72))
- 0xD3F97CDE70: 280E49B0DC8 (&"")
- 0xD3F97CDE78: 00000001 (1i | 1u)
- 0xD3F97CDE80: 280E4931690 (-> 0x280E92D1B40 -> &"")
- 0xD3F97CDE88: 001F0001 (2031617i | 2031617u)
- 0xD3F97CDE90: 00000001 (1i | 1u)
- 0xD3F97CDE98: 7FFD00000000 (140724603453440i | 0u)
- 0xD3F97CDEA0: 00000000 (0i | 0u)
- 0xD3F97CDEA8: 280E49321F0 (&"0")
- 0xD3F97CDEB0: 00000000 (0i | 0u)
- 0xD3F97CDEB8: 280E4D97810 (-> 0x101010101010001)
- 0xD3F97CDEC0: 28000000002 (2748779069442i | 2u)
- 0xD3F97CDEC8: 7FFE25A02E23 (ntdll.dll+0x52E23 (<0x52e10>+0x13))
- 0xD3F97CDED0: 800400021000 (140754668359680i | 135168u)
- 0xD3F97CDED8: 0000001D (29i | 29u)
- 0xD3F97CDEE0: A23DACEF014D (178385778049357i | 2901344589u)
- 0xD3F97CDEE8: 7FFE25A02E9C (ntdll.dll+0x52E9C (RtlGetExtendedContextLength2+0x3c))
- 0xD3F97CDEF0: 00000000 (0i | 0u)
- 0xD3F97CDEF8: 7FFE25A02D73 (ntdll.dll+0x52D73 (<0x52d58>+0x1b))
- 0xD3F97CDF00: 00000000 (0i | 0u)
- 0xD3F97CDF08: D3F97CEEC8 (&"2")
- 0xD3F97CDF10: 100000010 (4294967312i | 16u)
- 0xD3F97CDF18: 00000000 (0i | 0u)
- 0xD3F97CDF20: 0010000B (1048587i | 1048587u)
- 0xD3F97CDF28: 7FFE25A023FF (ntdll.dll+0x523FF (<0x52310>+0xef))
- 0xD3F97CDF30: 00000000 (0i | 0u)
- 0xD3F97CDF38: D3F97CE140 (&"")
- 0xD3F97CDF40: 4E8FFFFFB30 (5398773889840i | 4294966064u)
- 0xD3F97CDF48: 4D0FFFFFB30 (5295694674736i | 4294966064u)
- 0xD3F97CDF50: 00000019 (25i | 25u)
- 0xD3F97CDF58: 280E4D97801 (&"")

== Hardware Information ==
- CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (4 cores, 8 threads)
- GPU: Intel(R) Iris(R) Xe Graphics
- RAM: 16218 MB total, 6485 MB used, 9733 MB free
- SWAP: 2944 MB total, 1480 MB used, 1464 MB free
- OS: Windows Server, version 2004 amd64 (v.10.0.19041.4717)

**Comment by FireMario211** [comment]
Related to custom bg by camila314. Disable the mod to resolve the issue.

**Comment by Foxiseminger** [comment]
ok
