### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by ezpixelGD** [FireMario211/Object-Workshop#3]
The mod is outdated, and there is a bug where if you enter a page with a letter in it, the game crashes (i think)

**Comment by FireMario211** [comment]
> The mod is outdated, and there is a bug where if you enter a page with a letter in it, the game crashes (i think)

if the game crashes, send the crash log!
also i cant update the mod because im waiting for fig to accept my pr
https://github.com/FigmentBoy/GDAuth/pull/1
which as you can see, he hasnt
